name: todos
description: A todos application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^2.2.2
  flutter_bloc: ^6.0.6
  flutter_svg: ^0.19.1
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/





